DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS user CASCADE;

CREATE TABLE IF NOT EXISTS  product
(
    id INTEGER IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price int
);

CREATE TABLE IF NOT EXISTS  user
(
    id INTEGER IDENTITY  PRIMARY KEY,
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    success BOOLEAN
);
